org: lauranagamine
service: api-comentario

provider:
  name: aws
  runtime: python3.12
  memorySize: 1024
  timeout: 29
  iam:
    role: arn:aws:iam::004571481520:role/LabRole
  environment:
    TABLE_NAME: ${sls:stage}-t_comentarios
    INGEST_BUCKET: ${sls:stage}-bucket-ingesta-jr

functions:
  crear:
    handler: comentario.lambda_handler
    events:
      - http:
          path: /comentario/crear
          method: post
          cors: true
          integration: lambda

resources:
  Resources:
    TablaComentarios:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${sls:stage}-t_comentarios
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: uuid
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: uuid
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

    BucketIngesta:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${sls:stage}-bucket-ingesta-jr
        VersioningConfiguration:
          Status: Suspended